"use client";
import {Chart} from "./Plot";import type {AttributionContribution,HypotheticalShock,OptimizationStrategy,PortfolioResponse,RiskContribution} from "@/lib/types";import {STRATEGY_LABELS} from "@/lib/constants";
const navy="#173b57",blue="#2b6f9f",teal="#16847a",gold="#c28a2c",red="#bf4b4b",muted="#8aa0b4";
export function GrowthChart({data,benchmark}:{data:PortfolioResponse["cumulative_growth"];benchmark:string}){return <Chart ariaLabel="Portfolio and benchmark cumulative growth" data={[{type:"scatter",mode:"lines",name:"Portfolio",x:data.map(x=>x.date),y:data.map(x=>x.portfolio),line:{color:blue,width:2.5},hovertemplate:"Portfolio %{y:.3f}<extra></extra>"},{type:"scatter",mode:"lines",name:benchmark,x:data.map(x=>x.date),y:data.map(x=>x.benchmark),line:{color:muted,width:2},hovertemplate:`${benchmark} %{y:.3f}<extra></extra>`}]} layout={{yaxis:{title:{text:"Growth of $1"},tickformat:".2f"},legend:{orientation:"h",y:1.12}}}/>} 
export function DrawdownChart({data}:{data:PortfolioResponse["drawdown_series"]}){return <Chart ariaLabel="Portfolio drawdown through time" data={[{type:"scatter",mode:"lines",fill:"tozeroy",x:data.map(x=>x.date),y:data.map(x=>x.value),line:{color:red,width:1.5},fillcolor:"rgba(191,75,75,.14)",hovertemplate:"%{x}<br>%{y:.2%}<extra></extra>"}]} layout={{yaxis:{title:{text:"Drawdown"},tickformat:".0%"},showlegend:false}}/>}
export function AllocationChart({weights}:{weights:Record<string,number>}){return <Chart ariaLabel="Current portfolio allocation" height={310} data={[{type:"pie",hole:.62,labels:Object.keys(weights),values:Object.values(weights),textinfo:"label",textposition:"outside",marker:{colors:[navy,blue,teal,gold,red,"#6d6aa5"]},hovertemplate:"%{label}: %{value:.1%}<extra></extra>"}]} layout={{margin:{l:40,r:40,t:20,b:20},showlegend:false}}/>}
export function RiskContributionChart({rows,component=false}:{rows:RiskContribution[];component?:boolean}){return <Chart ariaLabel={component?"Component risk contribution":"Percent risk contribution"} data={[{type:"bar",x:rows.map(x=>x.ticker),y:rows.map(x=>component?x.component_risk_contribution:x.percent_risk_contribution),marker:{color:teal},hovertemplate:component?"%{x}: %{y:.4f}<extra></extra>":"%{x}: %{y:.2%}<extra></extra>"}]} layout={{yaxis:{title:{text:component?"Annualized contribution":"Share of risk"},tickformat:component?".3f":".0%"},showlegend:false}}/>}
export function CorrelationHeatmap({matrix}:{matrix:Record<string,Record<string,number|null>>}){const labels=Object.keys(matrix);return <Chart ariaLabel="Asset return correlation heatmap" data={[{type:"heatmap",x:labels,y:labels,z:labels.map(row=>labels.map(column=>matrix[row][column])),zmin:-1,zmax:1,colorscale:[[0,"#b44b5a"],[.5,"#f6f8fa"],[1,"#1d7187"]],hovertemplate:"%{y} / %{x}: %{z:.2f}<extra></extra>"}]} layout={{yaxis:{autorange:"reversed"},margin:{l:60,r:25,t:20,b:50}}}/>} 
export function ContributionChart({rows,active=false}:{rows:(AttributionContribution|{ticker:string;weighted_return_contribution:number})[];active?:boolean}){const values=rows.map(row=>active?(row as AttributionContribution).active_contribution:("portfolio_contribution" in row?row.portfolio_contribution:row.weighted_return_contribution));return <Chart ariaLabel={active?"Active contribution by asset":"Portfolio return contribution by asset"} data={[{type:"bar",orientation:"h",y:rows.map(x=>x.ticker),x:values,marker:{color:values.map(x=>x>=0?teal:red)},hovertemplate:"%{y}: %{x:.2%}<extra></extra>"}]} layout={{xaxis:{title:{text:"Contribution"},tickformat:".0%"},yaxis:{autorange:"reversed"},showlegend:false}}/>}
export function EfficientFrontierChart({frontier,strategies}:{frontier:OptimizationStrategy[];strategies:OptimizationStrategy[]}){return <Chart ariaLabel="Constrained efficient frontier and portfolio strategies" height={430} data={[{type:"scatter",mode:"lines+markers",name:"Efficient Frontier",x:frontier.map(x=>x.annualized_volatility),y:frontier.map(x=>x.expected_annual_return),text:frontier.map(x=>`Sharpe ${x.sharpe_ratio?.toFixed(2)??"—"}`),line:{color:blue,width:2},marker:{size:6},hovertemplate:"Volatility %{x:.2%}<br>Return %{y:.2%}<br>%{text}<extra></extra>"},{type:"scatter",mode:"text+markers",name:"Strategies",x:strategies.map(x=>x.annualized_volatility),y:strategies.map(x=>x.expected_annual_return),text:strategies.map(x=>STRATEGY_LABELS[x.strategy]??x.strategy),textposition:"top center",marker:{size:11,color:[navy,gold,teal,red,"#6d6aa5"]},hovertemplate:"%{text}<br>Volatility %{x:.2%}<br>Return %{y:.2%}<extra></extra>"}]} layout={{xaxis:{title:{text:"Annualized Volatility"},tickformat:".0%"},yaxis:{title:{text:"Expected Annual Return"},tickformat:".0%"},legend:{orientation:"h",y:1.14}}}/>} 
export function StressImpactChart({rows}:{rows:HypotheticalShock[]}){return <Chart ariaLabel="Hypothetical scenario portfolio impacts" data={[{type:"bar",x:rows.map(x=>x.name),y:rows.map(x=>x.total_portfolio_shock),marker:{color:rows.map(x=>x.total_portfolio_shock>=0?teal:red)},hovertemplate:"%{x}<br>%{y:.2%}<extra></extra>"}]} layout={{yaxis:{title:{text:"Portfolio Impact"},tickformat:".0%"},showlegend:false}}/>}
export function PeriodReturnsChart({rows,annual=false}:{rows:{date:string;value:number}[];annual?:boolean}){return <Chart ariaLabel={annual?"Annual portfolio returns":"Monthly portfolio returns"} data={[{type:"bar",x:rows.map(x=>x.date),y:rows.map(x=>x.value),marker:{color:rows.map(x=>x.value>=0?teal:red)},hovertemplate:"%{x}<br>%{y:.2%}<extra></extra>"}]} layout={{yaxis:{title:{text:annual?"Annual return":"Monthly return"},tickformat:".0%"},showlegend:false}}/>}
